# Generated by Django 2.0 on 2021-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('role_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
