# Generated by Django 2.0 on 2021-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemUser', '0004_titleui'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='user_type',
            field=models.CharField(default='USER', max_length=255),
        ),
    ]
