# Generated by Django 2.0 on 2021-10-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='storage/images/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=255)),
                ('total_bed', models.IntegerField()),
                ('total_bathsroom', models.IntegerField()),
                ('aria', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_love', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('related_item', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('total_room', models.IntegerField()),
                ('diensions', models.CharField(max_length=255)),
                ('garage', models.IntegerField()),
                ('year_build', models.CharField(max_length=255)),
                ('materials_ids', models.CharField(max_length=255)),
                ('feature_ids', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='image.Image'),
        ),
    ]
