# Generated by Django 2.0 on 2021-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_imageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image_url',
            field=models.ImageField(upload_to='storage/images/'),
        ),
    ]
