# Generated by Django 2.0 on 2021-10-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.ImageField(upload_to='storage/images/agencyCompany/')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('says', models.CharField(max_length=255)),
                ('image_url', models.ImageField(upload_to='storage/images/agencyCompany/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='agency.Agency')),
            ],
        ),
    ]
